### ISSUE TITLE
Run prettier for scss and other file types

### ISSUE THREAD

**Issue by rickyp-uber** [fusionjs/fusion-cli#351]
Fusion currently runs prettier via eslint for js files. It would be great if it also ran it for other file types that would exist, mainly the following:
 - Json
 - Markdown
 - Css
 - Less (if less is supported in fusion)
 - Scss

### Type of issue

Feature request

### Description

Wherever fusion is running prettier, to also run prettier for the other files listed

### Current behavior

Prettier only runs on js files

### Expected behavior

Prettier should run on most files applicable

**Comment by rtsao** [comment]
`fusion-cli` doesn't have a lint/prettier feature. There's [eslint-config-fusion](https://github.com/fusionjs/eslint-config-fusion) but that's typically used by eslint directly (via a  `package.json` script and `yarn run lint`).

I think originally this was an intentional decision to avoid bikeshed and so that the core build tooling doesn't abstract over linting. However, I think create-react-app does include some linting, so maybe it's worth revisiting being opinionated.

Alternatively, maybe just including a `yarn run prettier` package.json script would suffice.

**Comment by rickyp-uber** [comment]
You are right, it's in the eslint-config-fusion, my bad. It also seems to be running through the prettier eslint rules so I'm not sure what the integration point there would be yet. I'll close this out and move this request over there. Thanks!
