### ISSUE TITLE
Support dynamic plugin registering on future component

### ISSUE THREAD

**Issue by wheelo** [fusionjs/fusion-cli#621]
### Type of issue

Feature Request

### Description

I come from here, [fusion-react/issues/166](https://github.com/fusionjs/fusion-react/issues/166). In current fusion version, the functionality of code splitting is just loading the files with no bound to any context of your plugin, say redux or i18n plugin and etc. While code splitting may be quite useful to load files, users also want to lazily register related plugins after they route to some specific file.

### Current behavior

registering a plugin is only possible in the single entry file, e.g. the file `main.js`. 
`let app = new App(root); app.register(ReduxToken, Redux)`.

### Expected behavior

possible to dynamically register plugin on future component, e.g. the file `user.js`. In that file, user is able to access the `app` instance and inject redux plugin and new stores with `app.register(ReduxToken, Redux)`.
I think this is possible, as both of Koa context and React context is accessible in the future component.

### Your environment

* fusion-cli version: 1.13.0

**Comment by ganemone** [comment]
While I don't want to totally preclude the possibility of implementing some form of dynamic plugin registration, I will say that I think we need really strong use cases to warrant going in that direction. I think bundle splitting redux reducers is not a great use case.

The problem here is not with the fusion plugin architecture, but that redux was not designed in a way that supports bundle splitting effectively. Even if it is possible via store.replaceReducer, it is very risky and error prone.

A robust system would require the following guarantees:
- All reducers which handle action A are loaded before action A is dispatched
- All reducers which handle state B are loaded before any component connects to state B

Because dispatching actions, connecting components, and reducers are totally decoupled, you can't guarantee this. 

All redux issues aside, dynamic plugin registration is a very difficult problem, and I'm not sure it would be beneficial to increase the complexity of the DI system in such a way.

**Comment by wheelo** [comment]
I agree. Dynamic injection in `Redux` is not too hard to implement using replaceReducer which I've already put them to use. `Fusion` looks good to me right now, nothing in the architecture need be change.
